services:
  quizapp-web:
    container_name: quizapp-dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    env_file:
      - .env
    ports:
      - "3772:3000"
    volumes:
      - ./:/app
      # - /app/node_modules  # 컨테이너 내부 node_modules 유지
      - ./public/images:/app/public/images
      - ./public/uploads:/app/public/uploads
    environment:
      - NODE_ENV=${NODE_ENV}
      - HOSTNAME=${HOSTNAME}
      - NEXT_WEBPACK_USEPOLLING=false
      - WATCHPACK_POLLING=false
      - DEBUG=${DEBUG}
      - AUTHENTIK_HOST=${AUTHENTIK_HOST}
      - AUTHENTIK_CLIENT_ID=${AUTHENTIK_CLIENT_ID}
      - AUTHENTIK_CLIENT_SECRET=${AUTHENTIK_CLIENT_SECRET}
      - AUTHENTIK_ISSUER=${AUTHENTIK_ISSUER}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      # React Refresh 안정화를 위한 추가 설정
      - FAST_REFRESH=false
      - REACT_REFRESH_OVERLAY=false
      - NEXT_TELEMETRY_DISABLED=1
      # Webpack HMR 안정성을 위한 추가 설정
      - NEXT_WEBPACK_USEPOLLING=false
      - WATCHPACK_POLLING=false
      - WATCHPACK_AGGREGATE_TIMEOUT=500
      - NEXT_WEBPACK_IGNORED_WATCH_PATTERNS=node_modules,.git,.next,.env*
      # 모듈 로딩 안정성을 위한 설정
      - NODE_OPTIONS=--max-old-space-size=4096
      - NEXT_WEBPACK_OPTIMIZATION=true
    command: sh -c "npm run dev"
    networks:
      - ngnet
    depends_on:
      - quizapp-db
    # DNS 설정 추가 (외부 도메인 접근용)
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    # 외부 네트워크 접근을 위한 추가 설정 (제거 - 외부 도메인 접근 방해)
    # extra_hosts:
    #   - "auth.geniduck.org:172.18.0.2"
    #   - "quiz.geniduck.org:172.18.0.6"

  quizapp-db:
    image: postgres:16-alpine
    container_name: quizapp-db-dev
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${QUIZAPP_DB_USER}
      - POSTGRES_PASSWORD=${QUIZAPP_DB_PASSWORD}
      - POSTGRES_DB=${QUIZAPP_DB_NAME}
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ngnet

volumes:
  db_data_dev:

networks:
  ngnet:
    external: true
