version: '3.8'

services:
  web:
    container_name: quizapp-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "3772:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - ./public/images:/app/public/images
      - ./public/uploads:/app/public/uploads
    environment:
      - NODE_ENV=development
      - HOSTNAME=0.0.0.0
      - NEXT_WEBPACK_USEPOLLING=1
      - WATCHPACK_POLLING=true
      - DEBUG=openid-client:*
    command: sh -c "DEBUG=openid-client npm run dev"
    networks:
      - ngnet
    depends_on:
      - db
    dns:
      - 8.8.8.8
      - 1.1.1.1

  db:
    image: postgres:16-alpine
    container_name: quizapp-db-dev
    env_file:
      - .env
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ngnet

networks:
  ngnet:
    external: true

volumes:
  db_data_dev: 