services:
  web:
    build: .
    container_name: quizapp
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AUTHENTIK_HOST: ${AUTHENTIK_HOST}
      AUTHENTIK_CLIENT_ID: ${AUTHENTIK_CLIENT_ID}
      AUTHENTIK_CLIENT_SECRET: ${AUTHENTIK_CLIENT_SECRET}
      AUTHENTIK_ISSUER: ${AUTHENTIK_ISSUER}
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "3772:3000"
    volumes:
      - ./public/images:/app/public/images
      - ./public/uploads:/app/public/uploads
    networks:
      - ngnet

  db:
    image: postgres:16-alpine
    container_name: quizapp-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ngnet

networks:
  ngnet:
    external: true

volumes:
  db_data: 