version: '3.8'
services:
  web:
    build: .
    container_name: quizapp
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3772:3000"
    volumes:
      - ./public/images:/app/public/images
      - ./public/uploads:/app/public/uploads
    networks:
      - ngnet

  db:
    image: postgres:16-alpine
    container_name: quizapp-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ngnet

networks:
  ngnet:
    external: true

volumes:
  db_data: 